name: certbot-dns-cloudflare-cname
base: core24
summary: Cloudflare DNS Authenticator with CNAME support.
description: Cloudflare DNS Authenticator plugin for Certbot with support for CNAME aliasing.
grade: stable
confinement: strict
adopt-info: certbot-dns-cloudflare-cname
platforms:
  amd64:
  arm64:
  armhf:

parts:
  certbot-dns-cloudflare-cname:
    plugin: python
    source: .
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version "${SNAPCRAFT_PART_SRC}/setup.py" | cut -f2 -d= | tr -d "'[:space:]"`
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        snapcraftctl pull
        mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP\certbot-shared

